name: Float v1 branch

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  float-v1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - name: Push HEAD to v1
        run: git push origin HEAD:refs/heads/v1 --force
